AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API handler for api.buswatcher.org

Globals:
  Function:
    Timeout: 90

Resources:
  BusObservatoryHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src
      Handler: app.handler
      Runtime: python3.9
      MemorySize: 512
      Policies:
        - AWSGlueConsoleFullAccess
        - AmazonAthenaFullAccess
        - AmazonS3FullAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: 'arn:aws:secretsmanager:us-east-1:870747888580:secret:auth0_api.buswatcher.org-Mx25l5'
      Events:
        APIRoot:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref BusObservatoryApi

  BusObservatoryApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: 
        Type: REGIONAL
      Domain:
        DomainName: api.buswatcher.org
        CertificateArn: arn:aws:acm:us-east-1:870747888580:certificate/176e20fe-3a82-4499-bdc2-4be57a9284a9
        Route53:
          HostedZoneId: Z08217012WCG2ZG3GJ37P
