AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API handler for api.busobservatory.org
 
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      #TODO: define the privileges in this role in the Policies template below so this stack is standalone
      #Role: 'arn:aws:iam::870747888580:role/BusObservatoryAPI_Least_Privileged_Execution_Role'
      # https://aws.amazon.com/premiumsupport/knowledge-center/lambda-sam-template-permissions/
      Policies:
        - AWSGlueConsoleFullAccess
        - AmazonAthenaFullAccess
        - AmazonS3FullAccess
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: 'arn:aws:secretsmanager:us-east-1:870747888580:secret:auth0_api.busobservatory.org-Mx25l5'
      Handler: app.handler
      Runtime: python3.9
      Timeout: 300
      Architectures:
        - arm64
      MemorySize: 128
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
 
  #FIXME: this doesnt seem to do everything it needs to, in terms of API mappings
  #FIXME: had to go in and manually map the API to $default in API:custom domain names
  #FIXME: tho possible i just needed to wait a few more seconds for it activate (the CloudFormation log did indicate the API mapping was created)
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: api.busobservatory.org
        CertificateArn: arn:aws:acm:us-east-1:870747888580:certificate/d5dcd90b-2b51-4292-baec-2db004be6cec
        EndpointConfiguration: REGIONAL
        Route53:
          HostedZoneId: Z05676653JTHBS1DT8H1O
 
Outputs:
  ApiUrl:
    Description: ID of your API
    # Description: URL of your API
    Value:
      Fn::Sub: 'ID${Api}'
      # Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
