AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on Lambda Tutorial
 
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: app.handler
      Runtime: python3.9
      Timeout: 300
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
 
  Api:
    Type: AWS::Serverless::HttpApi
 
Outputs:
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'